### ISSUE TITLE
Memory issue, warnings and unit tests failures

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#197]
[Compile_output_tests.txt](https://github.com/Tudat/tudat/files/1019590/Compile_output_tests.txt)

[LastTest_log.txt](https://github.com/Tudat/tudat/files/1019600/LastTest_log.txt)

[issue_compilation_warnings_tudat.txt](https://github.com/Tudat/tudat/files/1019587/issue_compilation_warnings_tudat.txt)

Hi all,

I am working in the FullDevelopment branch and I had a memory issue together with many warnings while configuring the tudat. In attachment I am including the compile output as appeared on the screen. After managing to solve this issue by making more space in the RAM through cutting out other processes and changing some variable types in the codes, I encounter another issue when running the unit tests. The compile output and the LastTest log file related to the unit tests are also attached. Most of the errors are due to some tolerances that are not reached and others to the spice kernels loading. Although I load the spice kernels in the proper order there are still some issues with them. How shall I deal with this?

Thank you very much,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

Thanks for the update. I assume you refer to this issue: #183 right? In which files did you modify the kernel order? Did you recompile the unit test(s) _without_ the test compile argument in the project tab?

Let me know,

Dominic

**Comment by DominicDirkx** [comment]
Hi Giovanni,

Just to be sure, and since other people will also run into these issues, I corrected the kernel loading order in the FullDevelopment branch. Could you pull this branch from github, recompile (without the test compile argument in the project tab), rerun the tests, and post the output here? I also fixed some of the compile warnings you posted. If you run into any more, please also post them. 

To get the latest version of the branchh from github, open the git shell from smartgit: right-click on the tudat project and you'll see 'open git shell' or something along these lines. Make sure you right-click on the tudat _not_ the tudatBundle folder.

In the git shell, type:

git fetch upstream

This will retrieve the latest information on all the branches from GitFullDevelopmentBranchhub, but will not actually _do_ anything with them. Then, to update the code to the latest version, type:

git merge upstream/FullDevelopmentBranch

This will merge the latest version of the FullDevelopmentBranch branch from the upstream (github Tudat account) into your working branch. You may get some 'conflicts': meaning that your local changes are incompatible with the merge. If this occurs, it will tell you in which files the errors occur, and you can go to these files and modify them manually: both the old and new version of the code will show up in these kind of symbols:

<<<<<<<<<<<

========

>>>>>>>>

and you can choose to keep your local version of the code, or the new Tudat code by manually deleting what you don't want to keep.

Again, if anything goes wrong or you get stuck, please post the details of the problems you're running into here, and we'll get them fixed,

Cheers,

Dominic

**Comment by ggranato92** [comment]
Hi Dominic,

I have recompiled the unit tests but the errors still occur. I am now following the procedure you have described me above in order to update the Tudat code to compile and perform the tests again.

However, when I perform the merge in the git shell using the command you posted I get an abortion of the operation; this is in particular what shows up:

"Updating 6186221..ef74bd5
error: Your local changes to the following files would be overwritten by merge:
        Tudat/Astrodynamics/ObservationModels/UnitTests/unitTestOneWayDopplerModel.cpp
        Tudat/Astrodynamics/Propagators/UnitTests/unitTestMultiArcDynamics.cpp
Please commit your changes or stash them before you merge.
Aborting"

What shall I do at this point?

Thank you very much for your support,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

Ok, it seems that there are some inconsistencies between your modifications and the new code. Type

git stash

And then try again. After getting the new code, you can type 

git stash apply

To add your local modifications again,

Cheers,

Dominic

**Comment by ggranato92** [comment]
Hi Dominic,

I have managed to update the tudat and have compiled and run the tests again. Many tests now work properly but some of them still fail. I am attaching here the compile output and the last log file related to the unit tests. The spice kernels related problems seem disappeared with the exception of test_MutualSphericalHarmonicPartials. You can have a look at the details in the log file.

[Last_tests_log.txt](https://github.com/Tudat/tudat/files/1020447/Last_tests_log.txt)
[Compile_output.txt](https://github.com/Tudat/tudat/files/1020448/Compile_output.txt)

Thank you and best regards,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

Ok, great. I've had a look at the other failures, and have pushed some more fixes to the repository. Two should still fail:

- test_MultiArcStateEstimation If I recall correctly, we had to change the state/time type from long double/Time to double/double, which would explain the failures. Can you confirm that this is the case?
- test_SofaFundamentalArguments This one is a bit more unexpected. The tolerance in the test is already quite loose, and I'm a bit hesitant to put it looser without understanding what's happening. However, this test has no impact on your work, whatsoever, so no need to worry about it,

Cheers,

Dominic

**Comment by ggranato92** [comment]
Hi Dominic,

I am trying to pull the updated codes again but I am encountering a new error:

"$ git merge upstream/FullDevelopmentBranch
error: Merging is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict. "

I think the problem is that when I updated the code for the first time there were a couple of conflicts that I had to manually resolve (they concerned the files OneWayDopplerModel and the MultiArc one) and now that I'm trying to update again they create problems. What shall I do?

Thanks,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

You can do the same trick with 'git stash' again. I think it worked before (right?). You can also commit your local changes first, and then merge with the upstream

Cheers,

Dominic

**Comment by ggranato92** [comment]
Hi Dominic,

I have tried it but unfortunately it does not work now. This is what I get:

"$ git stash
Tudat/Astrodynamics/ObservationModels/UnitTests/unitTestOneWayDopplerModel.cpp: needs merge
Tudat/Astrodynamics/Propagators/UnitTests/unitTestMultiArcDynamics.cpp: needs merge
Tudat/Astrodynamics/ObservationModels/UnitTests/unitTestOneWayDopplerModel.cpp: needs merge
Tudat/Astrodynamics/Propagators/UnitTests/unitTestMultiArcDynamics.cpp: needs merge
Tudat/Astrodynamics/ObservationModels/UnitTests/unitTestOneWayDopplerModel.cpp: unmerged (b6a17139eff577bc5223d51491ee612f48755a36)
Tudat/Astrodynamics/ObservationModels/UnitTests/unitTestOneWayDopplerModel.cpp: unmerged (decfc38c8b0f477806e814ebe193d9bb655b2193)
Tudat/Astrodynamics/ObservationModels/UnitTests/unitTestOneWayDopplerModel.cpp: unmerged (b9e1b9ebd0f5e97f7746b2fc572c006095276304)
Tudat/Astrodynamics/Propagators/UnitTests/unitTestMultiArcDynamics.cpp: unmerged (821f26ac8d3d92571d724855acb05be0c7796e9e)
Tudat/Astrodynamics/Propagators/UnitTests/unitTestMultiArcDynamics.cpp: unmerged (066f7a4f5847989bf208baa68a7002f748b696a7)
Tudat/Astrodynamics/Propagators/UnitTests/unitTestMultiArcDynamics.cpp: unmerged (45a258b0a50270280e5ecf2cbbf73e0d2386b327)
fatal: git-write-tree: error building trees
Cannot save the current index state"

Any idea?

Thank you,
Giovanni

**Comment by DominicDirkx** [comment]
I think the merge went semi-successfully, there are just a few conflicts that need to be resolved. Have you solved these conflicts in the code? 

What do you get as output if you type 'git status'?

**Comment by ggranato92** [comment]
In the code there were some additional lines in both the doppler model and multi arc files with the symbols you described ("<<<<<< and =====") which determined errors so I removed them.

With git status I get the following:

"$ git status
HEAD detached from 6186221
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   Tudat/Astrodynamics/ObservationModels/UnitTests/unitTestAngularPositionModel.cpp
        modified:   Tudat/Astrodynamics/ObservationModels/UnitTests/unitTestOneWayDifferencedRangeModel.cpp
        modified:   Tudat/Astrodynamics/ObservationModels/UnitTests/unitTestOneWayRangeObservationModel.cpp
        modified:   Tudat/Astrodynamics/ObservationModels/UnitTests/unitTestPositionObservationModel.cpp
        modified:   Tudat/Astrodynamics/OrbitDetermination/AccelerationPartials/UnitTests/unitTestAccelerationPartials.cpp
        modified:   Tudat/Astrodynamics/OrbitDetermination/AccelerationPartials/UnitTests/unitTestMutualSphericalHarmonicPartials.cpp
        modified:   Tudat/Astrodynamics/OrbitDetermination/CMakeLists.txt
        modified:   Tudat/Astrodynamics/OrbitDetermination/ObservationPartials/UnitTests/unitTestPositionPartials.cpp
        modified:   Tudat/Astrodynamics/OrbitDetermination/UnitTests/unitTestMultiArcStateEstimation.cpp

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

        both modified:   Tudat/Astrodynamics/ObservationModels/UnitTests/unitTestOneWayDopplerModel.cpp
        both modified:   Tudat/Astrodynamics/Propagators/UnitTests/unitTestMultiArcDynamics.cpp "

**Comment by DominicDirkx** [comment]
Ok, good. First do:

git add Tudat

This will 'stage' all these files for commit. Then do 

git commit -m"[COMMIT MESSAGE]"

where [COMMIT MESSAGE] is the message that will show op in your git repo for this commit. By doing this, you will have added the current code to your local version control. Afterwards, you should be able to proceed with the next steps. Let me know if this works out,

Dominic

**Comment by ggranato92** [comment]
I have done that but when I do again 'git merge upstream/FullDevelopmentBranch' I get this:

Merge remote-tracking branch 'upstream/FullDevelopmentBranch' into HEAD

# Please enter a commit message to explain why this merge is necessary,
# especially if it merges an updated upstream into a topic branch.
# 
# Lines starting with '#' will be ignored, and an empty message aborts
# the commit

Shall I just press enter and continue?

Giovanni

**Comment by DominicDirkx** [comment]
Yeah, you get this sometimes, just continue and it'll be fine.

**Comment by ggranato92** [comment]
Hi Dominic,

I have managed to update the Tudat and have compiled everything again. In attachment I am sending you both the compile output with the warnings and the compile output related to the unit tests. Only three tests fail now and among them there are the two mentioned by you. 

Concerning the MultiArcStateEstimation test, I have also modified the time and state types from double to long double again and have run that single test again. However there are still warnings and the test fails. Attached is also the application output of this single test.

[Compile_output_new.txt](https://github.com/Tudat/tudat/files/1022790/Compile_output_new.txt)
[Last_test_log.txt](https://github.com/Tudat/tudat/files/1022794/Last_test_log.txt)
[Application_output_MultiarcStateEstimation.txt](https://github.com/Tudat/tudat/files/1022796/Application_output_MultiarcStateEstimation.txt)

Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

Thanks for the update. Are you sure that the (three) template arguments in MultiArcStateEstimation are the same as:

https://github.com/Tudat/tudat/blob/FullDevelopmentBranch/Tudat/Astrodynamics/OrbitDetermination/UnitTests/unitTestMultiArcStateEstimation.cpp

I've made a few more changes that should hopefully fix the warnings, and have made a small modifications that I hope will fix the MutualSphericalHarmonicPartials test. 

Don't worry about the Sofa test failing for now,

Dominic

**Comment by ggranato92** [comment]
Hi Dominic,

I have updated the code again and in attachment there are the new warnings (very few this time) and the new last test log file. As you can see, the MutualSphericalHarmonicPartials test still fails unfortunately.

I have checked my unitTestMultiArcStateEstimation file and this time I've made sure that is equal to yours here on github. (my bad, I had changed the template arguments as well yesterday). However, unfortunately when I build the file I have a memory issue when keeping the long double type in the parameterError vector. To make it work I have to put:

"Eigen::VectorXd parameterError = executeParameterEstimation<  double, tudat::Time,  double >( );"

but, as expected, then it fails..I am attaching the application output of this single test too.

[new_warnings.txt](https://github.com/Tudat/tudat/files/1025223/new_warnings.txt)
[Last_test_log.txt](https://github.com/Tudat/tudat/files/1025226/Last_test_log.txt)
[Application_output_MultiarcStateEstimation.txt](https://github.com/Tudat/tudat/files/1025228/Application_output_MultiarcStateEstimation.txt)

Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

Ok, try swapping the de and mars ephemeris files in the second test of the MutualSphericalHarmonicPartials test. Does this fix it?

Don't worry about the other tests, we can quickly discuss them on Monday,

Dominic

**Comment by ggranato92** [comment]
Hi Dominic,

I've tried several combinations when loading but unfortunately it still fails and the reason is still the same: insufficient ephemeris data has been loaded...

Thanks, see you on Monday then to discuss the other issues
Giovanni
