### ISSUE TITLE
Failure unit test: test_JsonInterfaceDeserialization

### ISSUE THREAD

**Issue by FrankHogervorst** [Tudat/tudat#275]
System: Windows 10 Education
This is the only unit test which is failing. 

```

Starting C:\dev\tudat\bin\unit_tests\test_JsonInterfaceDeserialization.exe...
Running 3 test cases...
C:/dev/tudat/Tudat/JsonInterface/UnitTests/unitTestDeserialization.cpp(155): error: in "test_json_deserialization/test_json_modular": check modular == simulation has failed [{"bodies":{"Earth":{"useDefaultSettings":true},"satellite":{"mass":500}},"export":[{"file":"export\\../outputs/epochs.txt","variables":[{"type":"independent"}]},{"file":"export\\../states.txt","variables":[{"body":"satellite","dependentVariableType":"relativePosition","relatieToBody":"Earth"},{"body":"satellite","dependentVariableType":"relativeVelocity","relatieToBody":"Earth"}]}],"integrator":{"stepSize":30,"type":"rungeKutta4"},"propagators":[{"bodiesToPropagate":["satellite"],"centralBodies":["Earth"]}]} != {"bodies":{"Earth":{"useDefaultSettings":true},"satellite":{"mass":500}},"export":[{"file":"export\\..\\outputs\\epochs.txt","variables":[{"type":"independent"}]},{"file":"export\\..\\states.txt","variables":[{"body":"satellite","dependentVariableType":"relativePosition","relatieToBody":"Earth"},{"body":"satellite","dependentVariableType":"relativeVelocity","relatieToBody":"Earth"}]}],"integrator":{"stepSize":30,"type":"rungeKutta4"},"propagators":[{"bodiesToPropagate":["satellite"],"centralBodies":["Earth"]}]}]

*** 1 failure is detected in the test module "Master Test Suite"
C:\dev\tudat\bin\unit_tests\test_JsonInterfaceDeserialization.exe exited with code 201
```

**Comment by DominicDirkx** [comment]
Hi Frank,

Could you add the unit test output file?

When did you pull this code from Github, Jacco merged all the latest changes this weekend (Tudat/tudat master branch)

**Comment by FrankHogervorst** [comment]
[LastTest.txt](https://github.com/Tudat/tudat/files/1445584/LastTest.txt)
 Pulled it before the weekend.

**Comment by FrankHogervorst** [comment]
Pulled latest version from Master branch, of Tudat and exampleApplications. Same problem:

[LastTest.log](https://github.com/Tudat/tudat/files/1460644/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1460645/LastTestsFailed.log)

**Comment by DominicDirkx** [comment]
For completeness, the same issue was reported by @oramireztorralba in #286 and @thijsmeneer in #285.

**Comment by DominicDirkx** [comment]
Brief update: this failure seems to be due to file directory naming being different in different operating systems/compilers. None of the functionality of the JSON interface seems to be broken, but the entry:

export":[{"file":"export\\../outputs/epochs.txt" 

is not equal to

"export":[{"file":"export\\..\\outputs\\epochs.txt"

Causing the unit test to fail. We will try to post a fix in the coming 1 or 2 weeks, pending the posting of other (possibly more pressing) unit test failures.

If this unit test fails for you, _**make sure to post your output as well**_. Your failure may have a different origin than this one.

**Comment by sangjae-park** [comment]
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1469436/LastTestsFailed.log)
[LastTest.log](https://github.com/Tudat/tudat/files/1469441/LastTest.log)

I hope one of the two files is the one you requested to post it here. 

-Kind regards-

**Comment by DominicDirkx** [comment]
Also reported in #288

**Comment by SebastianVillamil** [comment]
I received the same error I'm afraid 
[LastTest.log](https://github.com/Tudat/tudat/files/1472872/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1472873/LastTestsFailed.log)

**Comment by Morgonz** [comment]
I received the same error
OS : Windows 10
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1474011/LastTestsFailed.log)
[LastTest.log](https://github.com/Tudat/tudat/files/1474012/LastTest.log)

**Comment by gjherrero** [comment]
also failed with Windows 10. It says error 8.
[LastTest.log](https://github.com/Tudat/tudat/files/1474029/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1474030/LastTestsFailed.log)

**Comment by magnific0** [comment]
Another instance in in #292.

**Comment by Bobvannoort** [comment]
Hi,

On my laptop, unit test 190 also fails: the test_JsonInterfaceDeserialization. I have windows 10 as well. 
[LastTest.log](https://github.com/Tudat/tudat/files/1474467/LastTest.log)

**Comment by ViktorJordanov** [comment]
Hello,

Test 190 also failed for me. Windows 10
[LastTest.log](https://github.com/Tudat/tudat/files/1474476/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1474477/LastTestsFailed.log)

**Comment by lkoelemij** [comment]
[LastTest.log](https://github.com/Tudat/tudat/files/1474745/LastTest.log)
Windows 7 64-bit

**Comment by blagaune** [comment]
[LastTest.log](https://github.com/Tudat/tudat/files/1475217/LastTest.log)
Hi Dominic, Here's the requested output from the same 190 issue (#292)

Cheers

Bastiaan

**Comment by wjhuisman** [comment]
Hi Dominic,

The test also fails on my windows 10 system

[unit test fail.txt](https://github.com/Tudat/tudat/files/1478045/unit.test.fail.txt)

**Comment by azorzi** [comment]
Hi Dominic,
Test 190 fails on my Windows 10 (64-bit). I attach the requested file.
Kind regards,
Andrea
[LastTest.log](https://github.com/Tudat/tudat/files/1478418/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1478419/LastTestsFailed.log)

**Comment by ARBatchelor** [comment]
Hi Dominic,
Same issue for Json, but I also got an error for test 1. Should I open another issue?
OS: Windows 10 64 bit.

[LastTest.log](https://github.com/Tudat/tudat/files/1478781/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1478782/LastTestsFailed.log)

"The following tests FAILED:
	  1 - sofa-test (BAD_COMMAND)
	190 - test_JsonInterfaceDeserialization (Failed)
Errors while running CTest
Makefile:70: recipe for target 'test' failed
mingw32-make.exe: *** [test] Error 8
14:19:56: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"
14:19:56: Elapsed time: 15:05."

**Comment by DominicDirkx** [comment]
@ARBatchelor  No, that's fine. Could you open an issue for the "sofa-test (BAD_COMMAND)" though?

**Comment by lstubbig** [comment]
Another log-file with the same unit test failing from a 64bit Windows 10 machine
[LastTest.log](https://github.com/Tudat/tudat/files/1479506/LastTest.log)

**Comment by snigdhanarra** [comment]
Fails on Windows 10 , 
The following tests FAILED:
	190 - test_JsonInterfaceDeserialization (Failed)
Errors while running CTest
Makefile:71: recipe for target 'test' failed
mingw32-make.exe: *** [test] Error 8
11:39:36: The process "D:\SOFTWARES\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"
11:39:36: Elapsed time: 12:13.

**Comment by riccardobunt** [comment]
[LastTest.log](https://github.com/Tudat/tudat/files/1482416/LastTest.log)
hi Dominic,
I have the same problem on Windows 10 (64 bit)
Errors while running CTest
Makefile:70: recipe for target 'test' failed
mingw32-make.exe: *** [test] Error 8
13:57:07: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"

riccardo bunt
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1482422/LastTestsFailed.log)

**Comment by PaoloHaf** [comment]
Hello,
Same test failed, here are the log files I have :
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1482858/LastTestsFailed.log)
[LastTest.log](https://github.com/Tudat/tudat/files/1482859/LastTest.log)

**Comment by magnific0** [comment]
Dear all, I have just updated test_JsonInterfaceDeserialization test as part of d54205338f7599d024de8667aa694ea67b71a2fc

The test should now work. Can someone of you pull the new code and confirm this?

**Comment by SebastianVillamil** [comment]
Unfortunately, the test still fails for me. I tried both solution methods posted.
[LastTest.log](https://github.com/Tudat/tudat/files/1504251/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1504252/LastTestsFailed.log)

**Comment by ifodde** [comment]
Hello,
This issue is not yet closed and I got the same error as was said here:
190 - test_JsonInterfaceDeserialization (Failed)

here are my logs:
[LastTest.log](https://github.com/Tudat/tudat/files/1629263/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1629264/LastTestsFailed.log)

hope you can help me!

**Comment by magnific0** [comment]
@ifodde looking at your output log, I'm quite sure your code wasn't updated correctly. The issue was fixed. In case your doing the numerical astrodynamics course, please ignore the failed unit test and continue with the assignment.

Best,

Jacco

**Comment by ifodde** [comment]
@magnific0 I have to install tudat again for my Master thesis and I used the link in the installation guide to get the bundle, is this not the latest version? If not, do I need to pull the bundle and build it again?

Thanks in advance!

**Comment by magnific0** [comment]
Hi @ifodde Although the issue was indeed correctly fixed and updated in the Tudat repository on GitHub. The tudatBundle still linked to a version prior to this fix. This explains why you still exprienced the issue despite a very recent checkout. I have now fixed this. Please update you tudatBundle and tudat repositories.

You can verify this went according to plan by editing ```Tudat/JsonInterface/UnitTests/unitTestDeserialization.cpp``` and seeing whether it corresponds to the left-side of the following commit:
https://github.com/Tudat/tudat/commit/d54205338f7599d024de8667aa694ea67b71a2fc#diff-7de0ee9ddc4f454828a7513f379b8b48

Again, the error was a result of an improper test, not an issue with Tudat. So regardless, your installation is fine.

Let me know if you now have the latest version of everything.
