### ISSUE TITLE
Error 1 and Error 2 when building pagmo

### ISSUE THREAD

**Issue by roosmartens** [Tudat/tudat#621]
Dear Dominic,

While building pagmo (using -j2), I got the error attached below. I tried solving it using solutions to problems that looked similar, but this did not help. I am running from a Macbook with Mojave (do not know if this will be of any help). 

`In file included from /Users/roosmartens/tudatBundle/tudatExampleApplications/libraryExamples/PaGMOEx/cec2013OptimizerComparison.cpp:5:
/Users/roosmartens/tudatBundle/pagmo2/include/pagmo/problems/cec2013.hpp:36:2: error: The cec2013.hpp header was included but the CEC 2013 problem is not supported on the current platform.
#error The cec2013.hpp header was included but the CEC 2013 problem is not supported on the current platform.
 ^
1 error generated.
make[2]: *** [tudatExampleApplications/libraryExamples/PaGMOEx/CMakeFiles/application_PagmoCEC2013Comparison.dir/cec2013OptimizerComparison.cpp.o] Error 1
make[1]: *** [tudatExampleApplications/libraryExamples/PaGMOEx/CMakeFiles/application_PagmoCEC2013Comparison.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable /Users/roosmartens/tudatBundle/tudatExampleApplications/libraryExamples/bin/applications/application_PagmoEarthMarsTransferExample
[100%] Built target application_PagmoEarthMarsTransferExample
make: *** [all] Error 2
23:26:51: The process "/Applications/CMake.app/Contents/bin/cmake" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop (x86-darwin-generic-mach_o-32bit))
When executing step "CMake Build"`

**Comment by DominicDirkx** [comment]
Hi Roos,

I see you closed this issue, does that mean the problem is resolved?

Best,

Dominic

**Comment by roosmartens** [comment]
Oops, I think I closed it accidentally. It is still not resolved unfortunately.

**Comment by roosmartens** [comment]
These are my last log files.
[LastTest.log](https://github.com/Tudat/tudat/files/4392344/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/4392347/LastTestsFailed.log)

**Comment by DominicDirkx** [comment]
Please see issue #619 and #617, I think your problem is identical. If so, please confirm this and if the issue is resolved, close the issue.

If this fix does not correct your problem, let me know,

Dominic

**Comment by roosmartens** [comment]
Think I didn't scroll down enough before when seeing that post. Thanks! My only failing unit test now is 233:test_SimsFlanagan, so I think this is not a problem for the assignment right?
